#!/bin/bash

source git-lib
REPO=cashtpasswd
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=catalyst-authors --stdlayout http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Authentication-Store-Htpasswd/1.000/ ../${REPO}-export
cp ../${REPO}-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

git branch -D trunk
git branch -D trunk@5068
git branch -D trunk@5080

tag 0.02
tag 1.000
tag 1.001
tag 1.002
tag 1.003

git checkout master

git filter-branch  \
   --msg-filter '
      git fix-ghetto-message | sed -e "s/^- //"
   ' \
   --prune-empty \
   --tag-name-filter cat \
   -- --all

rm .git/refs/original -rf
