#!/bin/bash

source git-lib
REPO=cacopenid
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=catalyst-authors --stdlayout http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Authentication-Credential-OpenID/ ../${REPO}-export
cp ../${REPO}-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

# Wow...
git branch -D tags/0.02@10237
git branch -D tags/0.03@10237
git branch -D tags/0.03@7600
git branch -D tags/0.04@10237
git branch -D tags/0.04@7600
git branch -D tags/0.04@7934
git branch -D tags/0.05@10237
git branch -D tags/0.05@7600
git branch -D tags/0.05@7934
git branch -D tags/0.05@7935
git branch -D tags/0.06@10237
git branch -D tags/0.06@7600
git branch -D tags/0.06@7934
git branch -D tags/0.06@7935
git branch -D tags/0.06@8076
git branch -D tags/0.07@10237
git branch -D tags/0.07@7600
git branch -D tags/0.07@7934
git branch -D tags/0.07@7935
git branch -D tags/0.07@8076
git branch -D tags/0.07@8077
git branch -D tags/0.08@10237
git branch -D tags/0.08@7600
git branch -D tags/0.08@7934
git branch -D tags/0.08@7935
git branch -D tags/0.08@8076
git branch -D tags/0.08@8077
git branch -D tags/0.08@8083
git branch -D tags/0.09@10237
git branch -D tags/0.09@7600
git branch -D tags/0.09@7934
git branch -D tags/0.09@7935
git branch -D tags/0.09@8076
git branch -D tags/0.09@8077
git branch -D tags/0.09@8083
git branch -D tags/0.09@8472
git branch -D tags/0.10@10237
git branch -D tags/0.10@7600
git branch -D tags/0.10@7934
git branch -D tags/0.10@7935
git branch -D tags/0.10@8076
git branch -D tags/0.10@8077
git branch -D tags/0.10@8083
git branch -D tags/0.10@8472
git branch -D tags/0.10@8473
git branch -D tags/0.11@10237
git branch -D tags/0.11@7600
git branch -D tags/0.11@7934
git branch -D tags/0.11@7935
git branch -D tags/0.11@8076
git branch -D tags/0.11@8077
git branch -D tags/0.11@8083
git branch -D tags/0.11@8472
git branch -D tags/0.11@8473
git branch -D tags/0.11@8506
git branch -D tags/0.12@10237
git branch -D tags/0.12@7600
git branch -D tags/0.12@7934
git branch -D tags/0.12@7935
git branch -D tags/0.12@8076
git branch -D tags/0.12@8077
git branch -D tags/0.12@8083
git branch -D tags/0.12@8472
git branch -D tags/0.12@8473
git branch -D tags/0.12@8506
git branch -D tags/0.12@8511
git branch -D tags/0.13@10237
git branch -D tags/0.13@7600
git branch -D tags/0.13@7934
git branch -D tags/0.13@7935
git branch -D tags/0.13@8076
git branch -D tags/0.13@8077
git branch -D tags/0.13@8083
git branch -D tags/0.13@8472
git branch -D tags/0.13@8473
git branch -D tags/0.13@8506
git branch -D tags/0.13@8511
git branch -D tags/0.13@8684
git branch -D trunk@10237
git branch -D trunk@7600
git branch -D trunk@7934
git branch -D trunk@7935
git branch -D trunk@8076
git branch -D trunk@8077
git branch -D trunk@8083
git branch -D trunk@8472
git branch -D trunk@8473
git branch -D trunk@8506
git branch -D trunk@8511
git branch -D trunk@8684
git branch -D trunk

function tagr {
   _tag $1 refs/heads/tags/$1^^
   git branch -D tags/$1
}

# A couple of small dorky fixes (spelling/version) makes this 0.13 on the CPAN.
# A couple of small dorky fixes (spelling/version) makes this 0.13 on the CPAN.
# (with 0.13 version in Changes)
graft e57c476f24f11f03871a18274b9a6940d77a7efb beef7d51c03d6f51a798e4aecba70ed5dd98093e

# I think this is the 0.14 on the way up to the CPAN.
# How about we do our commits in trunk, so that we actually get sane linear revision history along the main development line of the code. Being able to actually use blame and log and diff to do something useful would be, well, useful.
graft c78e6460d0db01c9b6622d3c13a459f3118ef205 952b523cb0c935a75a194fac5e67c46662a7fa1c

tagr 0.02
tagr 0.03
tagr 0.04
tagr 0.05
tagr 0.06
tagr 0.07
tagr 0.08
tagr 0.09
tagr 0.10
tagr 0.11
tagr 0.12
tag 0.13
tag 0.14
tag 0.17
tag 0.18
tag 0.19

# nice ashley; you never checked 0.01 into svn.  Classy.
wget http://cpan.metacpan.org/authors/id/A/AS/ASHLEY/Catalyst-Authentication-Credential-OpenID-0.01.tar.gz
tar -xvzf Catalyst-Authentication-Credential-OpenID-0.01.tar.gz
mv Catalyst-Authentication-Credential-OpenID-0.01/* .
rmdir Catalyst-Authentication-Credential-OpenID-0.01
git checkout --orphan initial-branch
rm Makefile.PL Changes MANIFEST.skip lib t -rf
git add -A .
git commit -m 'initial commit' --author='Ashley Pond V <ashley@cpan.org>' --date='2008-04-06 00:00:00'
_tag 0.01 HEAD

graft 2607db75cf0f821df9fea063cd6b15f8fe264edb "$(git rev-parse HEAD)"

git checkout master

git filter-branch  \
   --prune-empty \
   --tag-name-filter cat \
   -- --all

rm .git/refs/original -rf
