#!/bin/bash

source git-lib
REPO=carenderview
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=catalyst-authors --stdlayout http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Action-RenderView/ ../${REPO}-export
cp ../${REPO}-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

git branch -D trunk
git branch -D trunk@5068
git branch -D trunk@9944

tag 0.10
tag 0.11
tag 0.13
tag 0.14
tag 0.15
tag 0.16

git checkout master

git filter-branch  \
   --prune-empty \
   --tag-name-filter cat \
   -- --all

rm .git/refs/original -rf
