#!/bin/bash

source git-lib
REPO=cpsession
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=catalyst-authors --stdlayout http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Session/0.00/ ../${REPO}-export
cp ../${REPO}-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

git branch -D trunk

git checkout master

git filter-branch  \
   --prune-empty \
   --tag-name-filter cat \
   --msg-filter 'git fix-ghetto-message' \
   --all

rm .git/refs/original -rf
