#!/bin/bash

source git-lib

REPO=dbicuuid
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=dbic-authors --trunk=trunk/DBIx-Class-UUIDColumns --tags=tags/DBIx-Class-UUIDColumns http://dev.catalyst.perl.org/repos/bast ../$REPO-export
cp ../$REPO-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

tag 0.01001
tag 0.02000
tag 0.02001
tag 0.02002
tag 0.02003
tag 0.02004
tag 0.02005

git branch -D trunk

git filter-branch  \
   --prune-empty \
   --msg-filter 'git fix-ghetto-message' \
   --tag-name-filter cat \
   -- --all

rm .git/refs/original -rf
