#!/bin/bash

rm -rf ../gic ../gic-pre-convert

git svn clone --no-metadata --authors-file=/home/frew/tmp/git/users --stdlayout svn://hg/GIC/gic ../gic-export
git svn clone --no-metadata --authors-file=/home/frew/tmp/git/users svn://hg/GIC gic-pre-convert-export

cp ../gic-export ../gic
cp ../gic-pre-convert-export ../gic-pre-convert

cd ../gic


# make "local" branches out of all the svn branches
cp .git/refs/remotes/* .git/refs/heads
git remote add pre file:///home/frew/code/OS/gic-pre-convert
git remote add cis-admin cs:cis-admin
git fetch pre
git fetch cis-admin


touch .git/info/grafts

echo "275dafb7ae678988fe8f5ce84162e091b22d06b8 " >> .git/info/grafts

unzip /home/frew/newshop.zip

git ci -am 'initial commit of newshop stuff'

#git filter-branch  \
   #--prune-empty \
   #--tag-name-filter cat \
   #-- --all



#rm .git/refs/original -rf
