#!/bin/bash

shopt -s dotglob
if [ -d sqlfairy ]
then
   mv sqlfairy/* .
fi
if [ -d CVSROOT ]
then
   rm -rf CVSROOT
fi
if [ -d htdocs ]
then
   rm -rf htdocs
fi
find . -name \*.swp -type f -delete
find . -name .cvsignore -type f -delete
