#!/usr/bin/env perl

use 5.12.0;
use warnings;


# r2279@metis (orig r1):  nwiger | 2006-09-28 04:06:33 +0100
# initial "import"

# should just be

# initial "import"

# ALSO

# r2298@metis (orig r20):  matthewt | 2007-02-07 13:46:06 +0000
#  r33610@cain (orig r9):  matthewt | 2006-11-13 09:14:03 +0000
#  abstract from code imported from DBIC::SQL::Abstract plus tests

# should just be

# abstract from code imported from DBIC::SQL::Abstract plus tests

# r5582@vger:  mendel | 2009-02-15 15:29:13 +0100
#  * Fixed a bug in hashpair with literal SQL and bind value (ie. col => { op => \[$sql, @bind] }) when bindty
#  * Added tests for hashpair with literal SQL and bind value (ie. col => { op => \[$sql, @bind] }) when bindt

# should just be

# Fixed a bug in hashpair with literal SQL and bind value (ie. col => { op => \[$sql, @bind] }) when bindty
# Added tests for hashpair with literal SQL and bind value (ie. col => { op => \[$sql, @bind] }) when bindt

my @out;
open my $fh, "<", "/home/frew/parentlist";
my @p = grep { $_ && $_ ne '-p' } split /\s/, <$fh>;
if (@p > 1) {
   my $x = `git name-rev --name-only $p[0]`;
   chomp $x;
   my $y = `git name-rev --name-only $p[1]`;
   chomp $y;
   print "Merge branch ($p[0]) $y into ($p[1]) $x"
} else {
   my @lines = <>;
   for (@lines) {
      unless (/^\s*r\d+\@\w+(\s+\(orig\s+r\d+\))?:\s+\w+\s+\|\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s+\+\d{4}\s*$/) {
         /(?:\s*)(?:\*\s+)?(.*)\s*/;
         push @out, $1;
      }
   }
}
print join "\n", @out;
