#!/bin/bash

function manual-tag {
   export GIT_COMMITTER_NAME=$4
   export GIT_COMMITTER_EMAIL=$5
   export GIT_COMMITTER_DATE=$6
   git tag "$1" -m "$2" "$3"
}

function __tag {
   manual-tag "v$1" "Release $1" $2 "$(git log $2 -1 --pretty=format:%an)" "$(git log $2 -1 --pretty=format:%ae)" "$(git log $2 -1 --pretty=format:%ai)"
}

function no_v_tag {
   COMMIT="$(git rev-parse $2)"
   manual-tag "$1" "Release $1" $2 "$(git log $COMMIT -1 --pretty=format:%an)" "$(git log $COMMIT -1 --pretty=format:%ae)" "$(git log $COMMIT -1 --pretty=format:%ai)"
}

function _tag {
   COMMIT="$(git rev-parse $2)"
   manual-tag "v$1" "Release $1" $2 "$(git log $COMMIT -1 --pretty=format:%an)" "$(git log $COMMIT -1 --pretty=format:%ae)" "$(git log $COMMIT -1 --pretty=format:%ai)"
}

function tag {
   _tag $1 refs/heads/origin/tags/$1
   git branch -D origin/tags/$1
}

function graft {
   touch .git/info/grafts
   echo "$@" >> .git/info/grafts
}
