#!/bin/bash

source git-lib
REPO=Perl-Critic
rm -rf ../$REPO

git svn clone --no-metadata --tags=tags --branches=branches --trunk=trunk/distributions/Perl-Critic svn://localhost ../${REPO}-export

cp ../${REPO}-export ../$REPO -r
cd ../$REPO

git branch -a | grep -v '* master' | cut -b11- | xargs -n1 -I{} sh -c 'git branch {} remotes/{} && git update-ref -d refs/remotes/{}'

git checkout master

git branch -D Perl-Critic-1.111
git branch -D Perl-Critic-1.109
git branch -D Perl-Critic-1.106
git branch -D Perl-Critic-1.052
git branch -D Perl-Critic-1.096
git branch -D Perl-Critic-1.xxx
git branch -D Perl-Critic-Config-Std
git branch -D Perl-Critic-PPI-1.203-cleanup
git branch -D Perl-Critic-PPI-1.204
git branch -D Perl-Critic-backlog
git branch -D Perl-Critic-ppi-performance-monkey-patch
git branch -D rt28120
git branch -D rt32616
git branch -D rt38855
git branch -D rt39601
git branch -D rt41942
git branch -D tags/Perl-Critic-0.23
git branch -D tags/Perl-Critic-1.07
git branch -D tags/Perl-Critic-1.071
git branch -D tags/Perl-Critic-1.079_001
git branch -D tags/Perl-Critic-1.079_002
git branch -D tags/Perl-Critic-1.079_003
git branch -D tags/Perl-Critic-1.081_001
git branch -D trunk
git branch -D Perl-Critic-Merge-Experiment
git branch -D old
git branch -D jeff
git branch -D chris
git branch -D chris2
git branch -D Perl-Critic-1.06-Plus-Perl-5.6-Compatibility-Fixes
git branch -D tags/Perl-Critic-Compatibility-0.999_001
git branch -D parameters
git branch -D Perl-Critic
git branch -D fix-utils-pod-t
git branch -D heredoc-regex-fix
git branch -D rt41443
git branch -D rt42458
git branch -D rt42384
git branch -D rt38530
git branch -D tpc_expose_critic_object_to_tests

git branch -a | grep @ | xargs -n1 -I{} git branch -D {}
git branch -a | grep TAP-Formatter | xargs -n1 -I{} git branch -D {}
git branch -a | grep Bundle-Perl-Critic | xargs -n1 -I{} git branch -D {}
git branch -a | grep PPIx-Utilities | xargs -n1 -I{} git branch -D {}
git branch -a | grep Task-Perl-Critic | xargs -n1 -I{} git branch -D {}
git branch -a | grep criticism | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-Dynamic | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-Deprecated | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-StricterSubs | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-Progressive | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-Moose | xargs -n1 -I{} git branch -D {}
git branch -a | grep Perl-Critic-More | xargs -n1 -I{} git branch -D {}
git branch -a | grep Test-Perl-Critic | xargs -n1 -I{} git branch -D {}

function tag {
   BRANCH="tags/Perl-Critic-$1"
   COMMIT="$(git show refs/heads/$BRANCH --pretty=%H)"
   manual-tag "v$1" "Release $1" $COMMIT "$(git show $COMMIT --pretty=format:%an)" "$(git show $COMMIT --pretty=format:%ae)" "$(git show $COMMIT --pretty=format:%ai)"
   git branch -D $BRANCH
}

tag 0.17
tag 0.18
tag 0.18_01
tag 0.19
tag 0.20
tag 0.21
tag 0.21_01
tag 0.22
tag 1.01
tag 1.02
tag 1.03
tag 1.04
tag 1.05
tag 1.051
tag 1.052
tag 1.053
tag 1.06
tag 1.061
tag 1.072
tag 1.073
tag 1.074
tag 1.075_001
tag 1.076
tag 1.077
tag 1.078
tag 1.081_002
tag 1.081_003
tag 1.081_004
tag 1.081_005
tag 1.081_006
tag 1.082
tag 1.083_001
tag 1.083_002
tag 1.083_003
tag 1.083_004
tag 1.083_005
tag 1.083_006
tag 1.084
tag 1.085
tag 1.086
tag 1.087
tag 1.089
tag 1.090
tag 1.091
tag 1.092
tag 1.093_001
tag 1.093_01
tag 1.093_02
tag 1.093_03
tag 1.094
tag 1.094001
tag 1.095_001
tag 1.096
tag 1.097_001
tag 1.097_002
tag 1.098
tag 1.099_001
tag 1.099_002
tag 1.100
tag 1.101_001
tag 1.101_002
tag 1.101_003
tag 1.102
tag 1.103
tag 1.104
tag 1.105
tag 1.105_001
tag 1.105_02
tag 1.105_03
tag 1.106
tag 1.107_001
tag 1.108
tag 1.109
tag 1.110_001
tag 1.111
tag 1.112_001
tag 1.112_002
tag 1.113
tag 1.114
tag 1.115
tag 1.116

# Fix URL to Dolan's post in Test::Perl::Critic -> Fix false statement in POD about ## no critic paying attention to
graft 737fbd32363fa086dec13b21241875feb215f682 1a6f90d697d3c6c094c98f4d3cf03d65e68a63b8

# stuff under Update Changes to reflect recent patches.
graft 3915a18b074f13de2be069c0d53fc1721de8e33c 056d124b4b291921dc941c377ef051bc336a6df5
graft 096c7749f5cd947673005267d2a69cfdebd40415 056d124b4b291921dc941c377ef051bc336a6df5
graft f0f431b5fe6583ae5d14eeadc5e950dc4f766b21 056d124b4b291921dc941c377ef051bc336a6df5
graft 34800350d9e4e4a1e443ca52fa64335b7863b98c 056d124b4b291921dc941c377ef051bc336a6df5
graft db3d15f7dccfeaa882c70e097cd980198647a1ba 056d124b4b291921dc941c377ef051bc336a6df5
graft 19811884861a0ed906b768bfbb7a5f42a3efe881 056d124b4b291921dc941c377ef051bc336a6df5
graft 227817d3ff62858c68bcdd68caec104d12046026 056d124b4b291921dc941c377ef051bc336a6df5

# Another attempt to tag version 0.20.
graft f34c35cabf32e444d86e01e551e158685c919388 cc3c19d352b897416b81a10c9d073317807d44a5

# *sigh.  Finally, a proper P::C 1.072 tag.
graft 9edff84cca5d070a8641de78316d28c2f997c9f7 41c583c7692c9f50d38d10931a341b32952ee074

# Retag P::C 1.075_001.
graft 3cb222e42c9846931a0711d9a65601fc9fdc8e31 83197d6091bbdc8ff05f80c2be5f436cc2f8add9

# Retag P::C 1.102 now that it's got the PPI 1.205 dependency in it.
graft 1df82ab914047fb3f801b3e391ce5b7be6b95f63 cc7e0b88e7e0ab79f219d1d156a644493843cb69

# Create branch for work on RT 64929, which requests a more-aggressive
graft 2919390bfec91d2ae3ddfcbd57488a0818c07e19 5eb3f3dc90804963f72a49a48c337cb71a1de41f

rm .git/refs/original -rf

rm ../tmp/$REPO -rf
git filter-branch  \
   --msg-filter 'git fix-prefix-messages' \
   --prune-empty \
   --tag-name-filter cat \
   --env-filter '
if [ "$GIT_AUTHOR_NAME" = "acmoore" ]; then export GIT_AUTHOR_NAME="Andrew Moore"; export GIT_AUTHOR_EMAIL="amoore@cpan.org"; fi
if [ "$GIT_AUTHOR_NAME" = "chrisdolan" ]; then export GIT_AUTHOR_NAME="Chris Dolan"; export GIT_AUTHOR_EMAIL="chris+github@chrisdolan.net"; fi
if [ "$GIT_AUTHOR_NAME" = "clonezone" ]; then export GIT_AUTHOR_NAME="Elliot Shank"; export GIT_AUTHOR_EMAIL="perl@galumph.com"; fi
if [ "$GIT_AUTHOR_NAME" = "glauschwuffel" ]; then export GIT_AUTHOR_NAME=" Gregor Goldbach"; export GIT_AUTHOR_EMAIL="goldbach@dfn-cert.de"; fi
if [ "$GIT_AUTHOR_NAME" = "jgilles" ]; then export GIT_AUTHOR_NAME=" Julien Gilles"; export GIT_AUTHOR_EMAIL="jgilles@tigris.org"; fi
if [ "$GIT_AUTHOR_NAME" = "jjore" ]; then export GIT_AUTHOR_NAME="Josh ben Jore"; export GIT_AUTHOR_EMAIL="twists@gmail.com"; fi
if [ "$GIT_AUTHOR_NAME" = "kyleha" ]; then export GIT_AUTHOR_NAME=" Kyle Hasselbacher"; export GIT_AUTHOR_EMAIL="kyleha@gmail.com"; fi
if [ "$GIT_AUTHOR_NAME" = "mgrimes" ]; then export GIT_AUTHOR_NAME="Mark Grimes"; export GIT_AUTHOR_EMAIL="mgrimes@cpan.org"; fi
if [ "$GIT_AUTHOR_NAME" = "misterwhipple" ]; then export GIT_AUTHOR_NAME="Edgar Whipple"; export GIT_AUTHOR_EMAIL="tigris@misterwhipple.com"; fi
if [ "$GIT_AUTHOR_NAME" = "mrwolf" ]; then export GIT_AUTHOR_NAME="Michael R. Wolf"; export GIT_AUTHOR_EMAIL="MichaelRWolf@att.net"; fi
if [ "$GIT_AUTHOR_NAME" = "petdance" ]; then export GIT_AUTHOR_NAME="Andy Lester"; export GIT_AUTHOR_EMAIL="andy@petdance.com"; fi
if [ "$GIT_AUTHOR_NAME" = "rcable" ]; then export GIT_AUTHOR_NAME="Rufus Cable"; export GIT_AUTHOR_EMAIL="rufus@threebytesfull.com"; fi
if [ "$GIT_AUTHOR_NAME" = "rjbs" ]; then export GIT_AUTHOR_NAME="Ricardo Signes"; export GIT_AUTHOR_EMAIL="rjbs@cpan.org"; fi
if [ "$GIT_AUTHOR_NAME" = "schwern" ]; then export GIT_AUTHOR_NAME="Michael G. Schwern"; export GIT_AUTHOR_EMAIL="schwern@pobox.com"; fi
if [ "$GIT_AUTHOR_NAME" = "shawnmoore" ]; then export GIT_AUTHOR_NAME="Shawn Moore"; export GIT_AUTHOR_EMAIL="sartak@gmail.com"; fi
if [ "$GIT_AUTHOR_NAME" = "smanuel" ]; then export GIT_AUTHOR_NAME="Subredu Manuel"; export GIT_AUTHOR_EMAIL="smanuel@tigris.org"; fi
if [ "$GIT_AUTHOR_NAME" = "thaljef" ]; then export GIT_AUTHOR_NAME="Jeffrey Ryan Thalhammer"; export GIT_AUTHOR_EMAIL="jeff@imaginative-software.com"; fi
if [ "$GIT_AUTHOR_NAME" = "williadd" ]; then export GIT_AUTHOR_NAME="Dustin Williams"; export GIT_AUTHOR_EMAIL="dustin_d_williams@yahoo.com"; fi
if [ "$GIT_AUTHOR_NAME" = "wyant" ]; then export GIT_AUTHOR_NAME="Tom Wyant"; export GIT_AUTHOR_EMAIL="harryfmudd@comcast.net"; fi
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME";
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL";
' \
   -d ../tmp/$REPO \
   -- --all

rm .git/refs/original -rf
