#!/bin/bash

# Note: I've commented out the SQLA2 stuff since we don't want that branch,
#       but it's an ok example of how you might integrate a couple weird
#       SVN repos together

git svn clone --authors-file=/home/frew/code/Haarg-convert/convert-git-dbic/authors --stdlayout http://dev.catalyst.perl.org/repos/bast/SQL-Abstract/2.000 sqla2
git svn clone --authors-file=/home/frew/code/Haarg-convert/convert-git-dbic/authors --stdlayout http://dev.catalyst.perl.org/repos/bast/SQL-Abstract/1.x sqla

cd sqla

# make "local" branches out of all the svn branches
cp .git/refs/remotes/* .git/refs/heads
git remote add sqla2 /home/frew/code/sqla2
git fetch sqla2

touch .git/info/grafts

# fix rob's fail
echo "66ea9a3e96731deb3ef3b86f9f2c90312eb87366 28c8cbc18b47bd8fcec5c433425e188845b46d25" >> .git/info/grafts

# fix ldami's fail
echo "19b49611ea0dd27a065ca523963b822de0849a66 08621652ee2124fbfcee2bbb8b42c2d59adee61d" >> .git/info/grafts

# my first fail (branch for SQL::Abstract::Tree!)
echo "ef73512183f83714333a487a1e229bfb6e5fcac2 aef8f7d74ad0a3347799ef66ed496c813823b12c" >> .git/info/grafts

# my second fail (YASQLATBranch)
echo "62e02eec5a0e82183bb881e4ba767f4bbc36e2db aef8f7d74ad0a3347799ef66ed496c813823b12c" >> .git/info/grafts

# branch commits lost due to rewriting so we can at least look at them for a while
git branch sqlat-1 a4d19942c440a3ad5bb10a12ee6127983c46e8d9
git branch sqlat-2 ef73512183f83714333a487a1e229bfb6e5fcac2

# The following branches were merged, so we delete them so that we don't have to rewrite them
git branch -d arbitrary_op_nesting
git branch -d test_refactor
git branch -d bool_operator
git branch -d special_op_handling
git branch -d and_or
git branch -d 1.50_RC
git branch -d trunk@3093
git branch -d trunk

## I use -d /tmp because it's a tmp-fs on my computer, so it should be faster
git filter-branch --msg-filter 'git fix-ghetto-message' \
   refs/heads/carp_debug refs/heads/cleanup refs/heads/fix_nesting \
   refs/heads/in_between refs/heads/1.50_RC-extraparens \
   refs/heads/log-sprintf refs/heads/master refs/heads/sqlat-1 \
   refs/heads/sqlat-2 refs/heads/sqla-tree

rm .git/refs/original -rf
rm .git/refs/remotes -rf


## ditch all pre-conversion objects forcefully
git reflog expire --all --expire=now
git gc --aggressive

git prune
git fsck --full

##git branch -D carp-debug
##git branch -D cleanup
##git branch -D fix_nesting
##git branch -D in_between
##git branch -D 1.50_RC-extraparens
##git branch -D 1.50_RC-extraparens
