#!/bin/bash

source git-lib
REPO=win32-daemon
PART=Win32-Daemon
rm -rf ../$REPO
git svn clone --no-metadata --authors-file=win32/authors --trunk=trunk/$PART --tags=tags/$PART http://libwin32.googlecode.com/svn/ ../${REPO}-export
cp ../${REPO}-export ../$REPO -r
cd ../$REPO
cp .git/refs/remotes/* .git/refs/heads/ -r
rm .git/refs/remotes -rf

git branch -D trunk

tag 20100921
tag 20101014
tag 20110117

git checkout master

git filter-branch  \
   --prune-empty \
   --tag-name-filter cat \
   -- --all

rm .git/refs/original -rf
